version: 2
updates:
  - package_ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency_name: "colorama"
      
  - package_ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
